const GET_ROLE_ACCESS = "GET_ROLE_ACCESS";
const GET_ROLE_TYPES = "GET_ROLE_TYPES";
const GET_USER_STORY_TYPES = "GET_USER_STORY_TYPES";
const ROLE_UPDATE = "ROLE_UPDATE";
const ROLE_SINGLE_DETAILS = "ROLE_SINGLE_DETAILS";

export default () => {
    return {
        GET_ROLE_ACCESS,
        GET_ROLE_TYPES,
        GET_USER_STORY_TYPES,
        ROLE_UPDATE,
        ROLE_SINGLE_DETAILS
    }
}
